"""initial schema

Revision ID: 02c935f1b1b4
Revises: 
Create Date: 2026-06-22 12:19:52.473827
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '02c935f1b1b4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('npi', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('detail', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_ledger_npi'), 'cost_ledger', ['npi'], unique=False)
    op.create_index(op.f('ix_cost_ledger_run_id'), 'cost_ledger', ['run_id'], unique=False)
    op.create_table('proposed_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('npi', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('field', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('old_value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('new_value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('field_confidence', sa.Float(), nullable=False),
    sa.Column('overall_confidence', sa.Float(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('supporting_sources', sa.JSON(), nullable=True),
    sa.Column('conflicting_sources', sa.JSON(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('llm_tier_used', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposed_changes_npi'), 'proposed_changes', ['npi'], unique=False)
    op.create_index(op.f('ix_proposed_changes_run_id'), 'proposed_changes', ['run_id'], unique=False)
    op.create_table('provider_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('npi', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=True),
    sa.Column('changed_fields', sa.JSON(), nullable=True),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_versions_npi'), 'provider_versions', ['npi'], unique=False)
    op.create_index(op.f('ix_provider_versions_run_id'), 'provider_versions', ['run_id'], unique=False)
    op.create_table('providers',
    sa.Column('npi', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('specialty', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('practice_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('active_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_verified_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('npi')
    )
    op.create_index(op.f('ix_providers_provider_id'), 'providers', ['provider_id'], unique=False)
    op.create_table('review_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('npi', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('recommendation', sa.JSON(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reviewer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_queue_npi'), 'review_queue', ['npi'], unique=False)
    op.create_index(op.f('ix_review_queue_run_id'), 'review_queue', ['run_id'], unique=False)
    op.create_index(op.f('ix_review_queue_status'), 'review_queue', ['status'], unique=False)
    op.create_table('runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('records_processed', sa.Integer(), nullable=False),
    sa.Column('no_change', sa.Integer(), nullable=False),
    sa.Column('auto_update', sa.Integer(), nullable=False),
    sa.Column('human_review', sa.Integer(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('npi', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_snapshots_content_hash'), 'source_snapshots', ['content_hash'], unique=False)
    op.create_index(op.f('ix_source_snapshots_npi'), 'source_snapshots', ['npi'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_snapshots_npi'), table_name='source_snapshots')
    op.drop_index(op.f('ix_source_snapshots_content_hash'), table_name='source_snapshots')
    op.drop_table('source_snapshots')
    op.drop_table('runs')
    op.drop_index(op.f('ix_review_queue_status'), table_name='review_queue')
    op.drop_index(op.f('ix_review_queue_run_id'), table_name='review_queue')
    op.drop_index(op.f('ix_review_queue_npi'), table_name='review_queue')
    op.drop_table('review_queue')
    op.drop_index(op.f('ix_providers_provider_id'), table_name='providers')
    op.drop_table('providers')
    op.drop_index(op.f('ix_provider_versions_run_id'), table_name='provider_versions')
    op.drop_index(op.f('ix_provider_versions_npi'), table_name='provider_versions')
    op.drop_table('provider_versions')
    op.drop_index(op.f('ix_proposed_changes_run_id'), table_name='proposed_changes')
    op.drop_index(op.f('ix_proposed_changes_npi'), table_name='proposed_changes')
    op.drop_table('proposed_changes')
    op.drop_index(op.f('ix_cost_ledger_run_id'), table_name='cost_ledger')
    op.drop_index(op.f('ix_cost_ledger_npi'), table_name='cost_ledger')
    op.drop_table('cost_ledger')
    # ### end Alembic commands ###
